- README.md
- src/scales.js
- src/scales/quantitative.js
> Add diverging-log et al.

- package.json
- test/output/usPopulationStateAgeArquero.svg
- test/plots/index.js
- test/plots/us-population-state-age-arquero.js
- yarn.lock
Testing arquero adds quite a few packages, but probably worth it.
> test arquero

- .gitignore
- test/plot.js
> create the test plot output if different from the expected value. 

- src/facet.js
> throw when facet is missing data

- rollup.config.js
Fixes #485. (Though, boo, I’m not sure why Rollup isn’t smart enough to tell that this is a side effect.)
> Style injection is a side effect

- README.md
- src/marks/rect.js
- test/output/stackedRect.svg
- test/plots/hadcrut-warming-stripes.js
- test/plots/index.js
- test/plots/stacked-rect.js
Fixes #429. Also supports zero-dimensional rects. 😉
> One-dimensional rect

- src/facet.js
- src/mark.js
- src/plot.js
- test/output/empty.svg
- test/plots/anscombe-quartet.js
- test/plots/empty.js
Supersedes #182. Fixes #292.
This also allows the marks to be null or undefined, which facilitates conditional marks. #127
> nullish and function marks

- src/scales/quantitative.js
- test/scales/scales-test.js
> expose range for continuous color scales

- README.md
(not super happy with the wording)
> document scheme range

- src/scales/quantitative.js
> limit maximum default radius

- src/marks/text.js
- src/style.js
- test/marks/text-test.js
> default round text strokeJoin

- src/legends/ramp.js
- test/output/colorLegendImplicitLabel.svg
- test/plots/legend-color.js
whether explicit or implicit
closes #605
(I'll have to update the documentation too :-) )
> An external legend should carry the label from the chart

- README.md
- src/transforms/group.js
- test/output/athletesBinsColors.svg
- test/plots/athletes-bins-colors.js
- test/plots/index.js
```js
Plot.plot({
marks: [
Plot.rectY(athletes, Plot.binX({fill: "x1", y: "count"}, {x: "weight"}))
]
})
```
> add extent reducers

- src/legends/swatches.js
- test/output/caltrain.html
- test/output/colorLegendCategorical.html
- test/output/colorLegendCategoricalReverse.html
- test/output/colorLegendCategoricalScheme.html
- test/output/colorLegendOrdinal.html
- test/output/colorLegendOrdinalScheme.html
- test/output/colorLegendOrdinalTickFormat.html
- test/output/colorLegendOrdinalTickFormatFunction.html
> flex-wrap swatches

- src/scales/schemes.js
> fix buylrd

- src/scales/schemes.js
- test/output/colorSchemesOrdinal.html
- test/output/colorSchemesQuantitative.html
- test/plots/legend-color.js
> test all color schemes

- src/defined.js
- src/scales/quantitative.js
- test/output/infinityLog.svg
- test/plots/index.js
- test/plots/infinity-log.js
> ignore non-finite values when inferring domain

- src/marks/text.js
- test/marks/text-test.js
> better fontSize disambiguation

- README.md
- src/marks/vector.js
- test/output/vectorFrame.svg
- test/plots/index.js
- test/plots/vector-frame.js
> vector frameAnchor

- README.md
- src/style.js
Ref. https://developer.mozilla.org/en-US/docs/Web/CSS/paint-order
Related #666 #667.
> paint-order

- README.md
aria-description support is apparently very scant at the moment, but hopefully it will get better.
> document aria-*

- src/legends.js
> a nullish legend should not be displayed as text "undefined"

- src/marks/rule.js
bug identified by @enjalot in https://github.com/observablehq/plot/discussions/855
> ruleX wasn't applying dx/dy

- src/channel.js
- src/options.js
- src/scales.js
> optimize channel type coercion

- README.md
- src/scales.js
- test/scales/scales-test.js
Propagate the global **zero** option just like we do with **nice** and **clamp**.
> global zero option

- README.md
> fix README: arrow default strokeWidth=1

- src/marks/area.js
- src/marks/arrow.js
- src/marks/bar.js
- src/marks/delaunay.js
- src/marks/dot.js
- src/marks/frame.js
- src/marks/hexgrid.js
- src/marks/image.js
- src/marks/line.js
- src/marks/linearRegression.js
- src/marks/link.js
- src/marks/rect.js
- src/marks/rule.js
- src/marks/text.js
- src/marks/tick.js
- src/marks/vector.js
- src/style.js
- test/output/bandClip.svg
- test/plots/band-clip.js
- test/plots/index.js
> clip supports band scales

- src/plot.js
Continuation of #953.
Ref. https://observablehq.com/@jkenzer/using-observable-notebooks-with-salesforce-com
Ref. https://talk.observablehq.com/t/using-plot-externally-unable-to-add-legend/6710
> appendChild instead of append

- package.json
- yarn.lock
> vite 3.0.0

- .eslintrc.json
- package.json
- src/data.ts
- src/options.ts
- test/types/options-test.ts
- yarn.lock
I wanted to send this to you before I got to bed, but it's not completed.
This is getting us in the direction of what @mythmon was talking about, where we can incorporate the type of the Datum as a generic throughout. I'm still confused in a lot of places as to what the code is supposed to do, so some of these changes are probably incorrect. But hopefully you can get something out of this anyway 🙏 
You can see that now if you call `valueof` on data with a certain shape you get the autocompletion for an accessor function for example:
> Some progress

- src/data.ts
- src/options.ts
- test/types/options-test.ts
- tsconfig.json
> valueof and map and arrayify types and tests

- CHANGELOG.md
This is just the changelog for v0.6.0. I haven't created the tag or updated package.json yet.
> v0.6.0 changelog

- test/plots/index.html
for an unknown reason the prettier github action now wants this on all the pull requests.
> prettier test/index.html

- src/scales/schemes.js
> improve unknown scheme errors

- src/transforms/group.js
- test/transforms/group-test.js
> preserve dates for mean and median

- README.md
> remove a TODO

- src/options.js
- test/options-test.js
> spaces are not numbers

- README.md
- src/style.js
> clip: "frame"

- src/projection.js
Simplified and inlined. (Plus, I tested manually all of insetLeft, insetRight, insetTop and insetBottom.)
> sharper translate

- scripts/readme-to-jsdoc.ts
thanks, @meetamit!
ref. https://github.com/observablehq/plot/pull/1096#issuecomment-1335941661
> allow readme-to-jsdoc.ts to run on windows

- README.md
Unless there was a reason not to document it? Couldn't find nor remember one.
> document the bundle curve

- README.md
> README edits for maps

- README.md
> document gridY, gridFx, gridFy

- src/marks/auto.js
- src/transforms/group.js
- test/output/autoAutoHistogram.svg
- test/plots/autoplot.js
> fix auto area

- src/channel.js
- test/output/athletesSortWeightLimit.svg
- test/plots/athletes-sort.ts
> null-safe sort

- src/transforms/map.d.ts
> document map

- src/scales.d.ts
- src/scales/index.js
> document scales

- README.md
- src/marks/hexgrid.d.ts
for #1343 
also bags a stray "layout" in README
> document hexgrid

- src/marks/delaunay.d.ts
> document delaunay

- src/marks/area.d.ts
- src/marks/delaunay.d.ts
- src/marks/density.d.ts
- src/marks/line.d.ts
> document density

- src/mark.d.ts
- src/marks/auto.d.ts
for https://github.com/observablehq/plot/issues/1343
> document auto

- src/facet.js
- src/plot.js
- test/output/usPopulationStateAgeGrouped.svg
- test/plots/us-population-state-age.ts
> fix imputed partial facet domain

- docs/.vitepress/markdown-it-plot.ts
- docs/data/bls-industry-unemployment.data.ts
- docs/data/bls-industry-unemployment.ts
- docs/data/sf-temperatures.data.ts
- docs/data/sf-temperatures.ts
- docs/data/us-presidential-election-2020.ts
- docs/features/projections.md
- docs/features/scales.md
- docs/marks/area.md
- docs/marks/arrow.md
- docs/marks/bar.md
- docs/marks/cell.md
- docs/marks/density.md
- docs/marks/image.md
- docs/marks/linear-regression.md
- docs/transforms/sort.md
- docs/transforms/window.md
a few changes across several files 🛫
todo:
> vitepress changes

- src/marks/image.d.ts
- src/marks/image.js
- test/output/kittenConstantRotate.svg
- test/output/kittenVariableRotate.svg
- test/plots/kitten.ts
> image rotate

- src/index.js
- src/options.d.ts
- src/options.js
- test/marks/cell-test.js
- test/marks/text-test.js
> expose indexOf, and use Uint32Array

- docs/marks/image.md
I’m a real penguin pedant now! Emailed Dr. Gorman for the photo, which she said we can use. Also changed in https://observablehq.com/@observablehq/plot-background-image. Brightened and cropped from the original.
|Original|Revised|
|-|-|
|![gorman-sea-ice](https://user-images.githubusercontent.com/841829/234958946-1480767e-662f-4eb3-9599-3ac39d7d4762.jpg)|![gorman-sea-ice-lighter-2](https://user-images.githubusercontent.com/841829/234958978-0f292c9c-8e0c-49dd-b8c8-1b926c161007.png)|
> Don’t confuse sea ice penguin habitat with deep interior habitat

- docs/why-plot.md
A little more on why Plot transforms are powerful.
> plot transforms data

- docs/features/marks.md
> mixed-up dimensions

- docs/transforms/map.md
- src/transforms/map.js
- test/output/shorthandLineYWindow.svg
- test/plots/shorthand-lineY.ts
> default identity map

- docs/components/PlotRender.js
- docs/marks/auto.md
This enables server-side rendering of interactive plots!
> better client-side hydration

- src/interactions/pointer.js
- src/marks/tip.js
When refactoring I accidentally made the tip mark aware of the **px** and **py** channels; it should ignore those channels.
Ref. https://observablehq.com/@observablehq/geo-shape-aware-pointer
> tip should ignore p[xy]

- src/marks/tip.js
- test/output/tipNewLines.svg
- test/plots/tip.ts
> tip: respect empty lines

- src/marks/tip.js
> default title to identity if text

- src/marks/tip.js
Like we do for *color*, but for *opacity*.
> tip opacity swatch

- src/plot.js
- test/output/tipGroupPrimitives.svg
- test/plots/tip.ts
> no implicit title on derived tip

- docs/transforms/centroid.md
> simpler geo label example

- docs/features/legends.md
> document className suffix in legends

- package.json
- yarn.lock
> chore: upgrade vitepress to fix instant search detailed view

- docs/.vitepress/config.ts
/plot/ is missing from https://observablehq.com/plot/sitemap.xml
> fix sitemap

- docs/marks/axis.md
> fix facetAnchor interactive doc crashing when it receives "null"

- src/options.js
- test/output/mixedFacets.svg
- test/plots/index.ts
- test/plots/mixed-facets.ts
> fix crash during reindex

- src/plot.js
- test/output/percentNull.svg
- test/plots/index.ts
- test/plots/percent-null.ts
> don’t coerce null percent to zero

- docs/.vitepress/config.ts
- docs/features/plots.md
- docs/getting-started.md
Inadvertently removed in #2191.
> add examples to sidebar

- docs/data/api.data.ts
for the ChannelDomainOptions options: reduce, order, reverse, and limit
as mentioned in https://github.com/observablehq/plot/discussions/2293#discussioncomment-12431097
> add API links to https://observablehq.com/plot/features/scales 
