observablehq/plot

src/marks/text.js
This fixes them on Firefox (which objected to font-size being unitless).
=> Use attrs for font properties

src/mark.js, test/marks/area-test.js, test/marks/bar-test.js, test/marks/cell-test.js, test/marks/dot-test.js, test/marks/line-test.js, test/marks/link-test.js, test/marks/rect-test.js, test/marks/rule-test.js, test/marks/text-test.js, test/marks/tick-test.js
Instead, leave them as-is, and let valueof (and labelof) do the work. Broken out of #451.
=> Don’t promote string channel values to functions.

src/facet.js
There doesn’t seem any advantage to the more cryptic error if you specify facet: {data: null}, so might as well use the lax test here.
Note that facet: {data: false} does _not_ error, and is similar to facet: {data: []}. I think that’s appropriate.
=> Nice error for null facet data

README.md, src/transforms/group.js, test/output/wordLengthMobyDick.svg, test/plots/word-length-moby-dick.js
the plot example shows the most common word of length x as a title for each bar
closes #420
(cherry-pick of ea9f8cdf8e0181d748a8175b664e690e0dcd0183)
=> add the *mode* aggregation

src/plot.js
=> ignore null transform

src/transforms/select.js
=> explicit error message when the required channel is missing in selectMaxX

test/plot.js
(I think it disappeared after 13052a87 when assert replaced test.ok)
=> reinstate the "save changed figure" functionality of tests

src/marks/link.js
Fixes #428. I mirrored the approach from the area mark so that we don’t need to compute both channels when only one is needed.
=> Shorthand for axis-aligned links

README.md, src/transforms/bin.js
(see #417)
(200 is working for almost any chart size; 100 would be a fine choice too)
=> cap the default number of bins at 200

src/facet.js, src/mark.js, src/marks/area.js, src/marks/bar.js, src/marks/dot.js, src/marks/frame.js, src/marks/line.js, src/marks/link.js, src/marks/rect.js, src/marks/rule.js, src/marks/text.js, src/marks/tick.js, src/plot.js, src/scales.js, src/style.js, test/marks/frame-test.js
Related #322, this is a sketch at how we might consolidate the definition of “standard” channels in Plot. This idea is to define them in one place so that we can add a new standard channel to all marks with less risk of drift between marks.
~~This only currently works for the Area mark. In addition to porting the other marks to use this system, we need to address that some marks have different defaults (for example Line has a default stroke, whereas Area has a default fill), and that some marks have different structure (for example Area and Line produce a single path element per series and thus group styles, whereas Dot and Bar product distinct elements for each data point).~~ I’ve done most of this now.
TODO
If you like this idea I’d be happy to continue work and/or work on it together.
=> Common style channels

README.md, src/style.js
closes #311
build : https://observablehq.com/@fil/plot-strokewidth-322
=> strokeWidth as a channel

src/facet.js, src/mark.js, src/marks/bar.js, src/marks/frame.js, src/marks/rect.js, src/marks/rule.js, src/marks/text.js, src/scales.js, test/output/singleValueBar.svg, test/output/singleValueBin.svg, test/plots/index.js, test/plots/single-value-bar.js, test/plots/single-value-bin.js
Supersedes #438.
Ref. https://github.com/observablehq/plot/issues/417#issuecomment-849149359.
This adds special logic to marks with continuous position dimensions such that when the associated scale’s domain is collapsed (i.e., all values in the input domain map to the same value in the output range), the mark spans the full extent of the chart. For example, here is a plot with the collapsed _y_-domain [0, 0]; note that the bar and rule span the full _y_-extent of the chart. Previously this chart would be empty because the bar and rule would have zero height.
```js
Plot.plot({
marks: [
Plot.barY({length: 1}, {x: ["foo"], y1: [0], y2: [0]}),
Plot.ruleX(["foo"], {stroke: "red", y1: [0], y2: [0]})
]
})
```
In practice, this seems most likely to occur when binning values that all happen to be …
=> handle collapsed domains

README.md, src/transforms/normalize.js, src/transforms/stack.js, src/transforms/window.js, test/plots/cars-parcoords.js, test/plots/gistemp-anomaly-moving.js, test/plots/metro-unemployment-moving.js, test/plots/us-population-state-age-dots.js, test/plots/us-population-state-age.js
This PR allows transform options to be kept separate from passthrough options, as well as shorthand options for the normalize and window transforms. Explicit transform options can disambiguate the intended recipient of the options, which could be a specific transform in a sequence of transforms or the output mark. This is especially important for the stack option’s _reverse_ option, which overlaps with the basic reverse transform.
Supersedes #480.
Supersedes #439.
Related #472.
Fixes #479.
=> Explicit transform options

README.md, src/transforms/stack.js, src/transforms/window.js, test/transforms/windowMax-test.js, test/transforms/windowMean-test.js
These are for consistency with Vega-Lite:
* offset = center is an alias for offset = silhouette
* offset = normalize is an alias for offset = expand
Although, I thought maybe offset = proportion should be an alias for offset = expand, given that we support a proportion reducer? Though it’s not exactly the same thing. We could have multiple aliases, I suppose, to help people with familiarity with other libraries.
=> offset = {center, normalize}

README.md, src/axis.js, test/output/athletesSportWeight.svg, test/plots/athletes-sport-weight.js
handy for materializing the vertical axis of a bar chart with an ordinal x
note that in the case of a continuous *X*, tickX([*extent min*]) is often preferable, since it creates the support line for all x/y facets
see https://observablehq.com/@fil/axis-support-406
suggested by @ee2dev
=> add a {line: true} option to axes

README.md, src/mark.js, src/transforms/stack.js, test/data/first-ladies.csv, test/output/firstLadies.svg, test/plots/first-ladies.js, test/plots/index.js
* README document sort x by y
* first ladies example plot (by @tophtucker )
* add limit: [lo, hi]
* throw the correct error if a mistaken sort option is given as {x: "-y", limit: 10}
=> a few changes

src/mark.js, test/plots/athletes-nationality.js, test/plots/athletes-sport-sex.js, test/plots/ballot-status-race.js, test/plots/d3-survey-2015.js, test/plots/metro-unemployment-ridgeline.js, test/plots/movies-profit-by-genre.js, test/plots/us-population-state-age-dots.js
If a *sort* option is expressed as a function rather than a channel name, treat it as a data reducer. In the ballotStatusRace example this allows the facets to be sorted by percent accepted.
=> allow sort to reduce data

package.json
The `src/style.css` file is not kept in the distributed ES module. If I understand correctly, keeping it would allow to import it directly and keep it up to date when using Plot from a package manager.
=> Keep style.css in ES module

README.md, src/mark.js, src/marks/area.js, src/marks/bar.js, src/marks/dot.js, src/marks/frame.js, src/marks/line.js, src/marks/link.js, src/marks/rect.js, src/marks/rule.js, src/marks/text.js, src/marks/tick.js, src/style.js
On all marks except text, dx, dy are rendered as a transform(translate) or (x,y) property, possibly with the 0.5px offset on high-density screens. On text marks, the dx and dy properties are used.
closes #379
build : https://observablehq.com/@fil/plot-dx-dy-488 ; also available in https://observablehq.com/@fil/plot-early-bird
=> support dx, dy on all marks

src/axis.js
Fixes #544.
Since I was there, I also took a moment to rewrite the code so to make slightly fewer assumptions about the structure of the axis: namely, rather than only looking at the first element’s attributes, look at each element individually. I don’t seeing this having any immediate practical effect, but it does seem slightly cleaner.
There aren’t any tests for the tickRotate option. Any chance you’d be willing to add some to make sure I haven’t broken anything here, @Fil?
(I tested it in [this notebook](https://observablehq.com/d/d3feddc757b564e2) and it seemed to still work…)
=> handle no ticks when rotating

src/scales/quantitative.js, test/scales/scales-test.js
Plot scales always produce numbers or colors, so we don’t need the generality here, and it’s (ever so slightly) faster to avoid it.
=> interpolateNumber by default

src/scales.js, test/plots/google-trends-ridgeline.js, test/plots/metro-unemployment-ridgeline.js
Fixes #547. I think this is nice because it is easily interpreted: we’ll never introduce more than 30px of wasted space due to automatic rounding.
=> auto-round based on wasted space

src/scales/diverging.js, test/scales/scales-test.js
Rather than truncating the interpolator, this extends the domain so that it is symmetric around the pivot. While the effect is the same internally, this has two improvements.
First, it fixes #562 by returning a domain that is already symmetric, and hence applying the (default) symmetric transform again is idempotent and has no effect.
Second, it makes it easier to produce a good color legend for symmetric diverging scales. With the previous approach, you’d see something like this:
While strictly accurate, it’s a bit visually unsettling and difficult to interpret. The lower half of the legend is given equal visual space to the upper half, but covers a smaller range of values ([-0.78, 0] vs. [0, 1.35]). Under the new approach in this PR, you’d instead get:
The extended domain includes …
=> symmetric diverging scales by domain extension

src/scales.js, src/scales/quantitative.js
Fixes a crash where we tried to pass an undefined *range* to the scaleQuantile and scaleThreshold constructors, and then fixes an off-by-one in autoScaleRange for threshold scales, which require a range of length domain.length + 1.
=> allow quantile or threshold position scales

README.md, src/scales.js, test/scales/scales-test.js
(Note that diverging scales do not expose invert, as per d3-scale.)
=> scale("x") builds scale.apply and (when applicable) scale.invert

README.md, src/legends.js, src/legends/opacity.js, src/mark.js, test/output/opacityLegend.svg, test/output/opacityLegendColor.svg, test/output/opacityLegendLinear.svg, test/output/opacityLegendLog.svg, test/output/opacityLegendRange.svg, test/output/opacityLegendSqrt.svg, test/plots/index.js, test/plots/legend-opacity.js
A ramp with increasing opacity.
We need to test various possibilities; maybe a checkered background would be nicer; maybe swatches might be useful for some types of opacity scales.
=> opacity legend

README.md
it's a bit unintuitive at first how this interacts with columns, but the plot-legends notebook helps to clarify
=> document *width* for swatches legend

src/scales/schemes.js, test/output/colorSchemesOrdinal.html
Fixes burd and buylrd with n=2:
Fixes turbo, virdis et al. with n=1:
Fixes warm and cool with n=1:
I decided to leave cubehelix as-is, since that’s how the scheme is designed.
=> fix quantized ordinal color schemes

README.md, src/transforms/window.js
Ref. https://github.com/observablehq/plot/discussions/635#discussioncomment-1888720
=> add first and last reducers for window

README.md, src/index.js, src/scales.js, test/scales/scales-test.js
Alternative to #625. This lets you create the standalone scale directly, without requiring either a legend or a chart (but you can pass the scale to either as desired). Fixes #624.
=> standalone scales with Plot.scale

src/marks/dot.js, src/marks/image.js, src/marks/text.js, src/transforms/interval.js
I prefer to keep the two transforms distinct: we’ll compute the midpoint of the interval for dot, text, and image, and the extent of the interval for other marks. This also allows the “mid” interval transform to avoid memoization.
In addition to your fix to pass *data* to the interval’s transform function in case x2 in computed before x1, I’ve also fixed the memoization to be bypassed if the *data* changes. This isn’t currently possible in Plot, but I could imagine us wanting to support data changing in the future, so fixing while I’m here.
=> “mid” interval transform

src/scales.js, test/scales/scales-test.js
Alternative to #618. Fixes #616. This behavior is more consistent with how rects treat insets, e.g.,
https://github.com/observablehq/plot/blob/72b2adbc28ed12a2fb2de800af8b57bd14a63154/src/marks/rect.js#L57-L60
I’d slightly prefer using the midpoint here, something like:
```js
if (right >= left) {
scale.range = [left, right];
} else {
const center = (right + left) / 2;
scale.range = [center, center];
}
```
But then I’d want rects to behave similarly, and I don’t think it’s really worth the trouble for such a rare thing. Mostly I just want to avoid the surprising (to me) behavior of the scale’s range getting inverted when the insets or margins are too big, and I think a collapsed range is a sufficient indication of a misconfiguration and we don’t need to do more.
=> don’t allow margins or insets to invert range

src/legends/ramp.js, test/output/colorLegendLinearNoTicks.svg, test/plots/legend-color.js
(unifies ramp and swatches)
this is equivalent to setting 0 ticks; an alternative could be to set tickFormat to () => "". I have no preference on the matter.
=> tickFormat: null should not create ticks

src/channel.js, src/defined.js, src/marks/area.js, src/marks/bar.js, src/marks/cell.js, src/marks/dot.js, src/marks/image.js, src/marks/line.js, src/marks/link.js, src/marks/rect.js, src/marks/rule.js, src/marks/text.js, src/marks/tick.js, src/marks/vector.js, src/options.js, src/plot.js, src/scales.js, src/style.js, test/marks/text-test.js
Takes the filter(index, ...channels) function and incorporates it into plot.js (and facet.js) so that filtering is more declarative and happens by default. You can opt-out of filtering by declaring filter: null (as for lines and areas) or to specify a custom filter definition.
This is groundwork for layouts (e.g., dodge #648)
=> universal channel filter

README.md
It took me a little while to track down exactly what format specifiers I can use with `scale.tickFormat`. I thought it would be useful if links to the [d3-format](https://github.com/d3/d3-format#locale_format) and [d3-time-format](https://github.com/d3/d3-time-format#locale_format) format specifier docs were included in the README, to help fellow travellers.
=> Add info to README on what's available for scale.tickFormat

README.md, src/index.js, src/transforms/select.js, test/output/athletesSample.svg, test/output/industryUnemploymentTrack.svg, test/plots/athletes-sample.js, test/plots/index.js, test/plots/industry-unemployment-track.js
demo: https://observablehq.com/@observablehq/plot-select-generalize-656
closes #515
*select a sample:*
*select min and max of a color:*
=> generalize Plot.select

README.md, src/marks/arrow.js
It probably fails in some cases and I didn’t try too hard to optimize it, but it seems to work in the easy cases. 🤷
=> arrow insets

src/options.js, src/scales.js
Amendment to #673 and alternative to #660 and #675. I think this is my preference because it feels more semantic than using an ordinal scale (even though this means you won’t get a legend, but I don’t think you want a legend for an identity scale). And unlike #673 alone this will reduce the likelihood of false positives since *all* defined values must be valid CSS colors. That’s a bit more strict than we usually do, but I think it’s okay since there isn’t a special type for colors and hence we must test strings.
=> only identity if all values are colors

src/transforms/bin.js, src/transforms/group.js, test/output/penguinMassSpecies.svg, test/plots/penguin-mass-species.js
=> propagate title and href by default

src/scales/ordinal.js, src/scales/schemes.js, test/output/colorSchemesOrdinal.html, test/scales/scales-test.js
When the defined values associated with an ordinal or categorical color scale are entirely boolean (true or false), construct a default range from the *greys* color scheme, assigning the light gray to false and the dark gray to true (rather than *turbo* or *tableau10*). In addition, make the *n* = 2 ordinal schemes higher contrast by favoring the extrema.
I considered having categorical color scales continue to use *tableau10*, restricting this behavior to ordinal color scales. This would require changing the logic in asOrdinalType to similarly check whether the associated defined values are boolean. I wasn’t sure if it was desirable to do this check twice. And I went back and forth over whether this should be an exhaustive check or a fast check (looking only at the first defined value). …
=> boolean greys

src/options.js
We do this for number and date, so we should for boolean, too. Previously #346.
=> promote boolean to constant

README.md
Adding a link to the cheatsheets from the `README.md` file. Feel free to suggest alternative placements or language. 
Note: not ready for to merge as the notebook is not yet publicly visible, and the PDFs are still being edited.
=> Add cheatsheet link

README.md, src/marks/text.js, test/output/mobyDick.svg, test/plots/index.js, test/plots/moby-dick.js
Implements text wrapping using a *lineWidth* option on the text mark. Fixes #688. Tasks:
Even though this is very rudimentary, I think it will be super useful and can be improved in the future based on usage.
I think the biggest blocker is just whether it’s okay to have *lineWidth* in ems. That’s the easiest thing for us to implement based on the baked-in rudimentary text metrics, but I think people are likely to get confused because they are more likely to be thinking in pixels. The problem with pixels is that the *fontSize* isn’t necessarily in pixels, either #378 and so we’d almost certainly need to invoke the browser’s full text metrics in order to compute it. And that also means an element will need to be attached to the DOM, and it’s slow, etc. So, I think maybe *lineWidth* in ems …
=> text wrap (lineWidth)

src/style.js
CSS/SVG ignores case and surrounding whitespace, so we should, too.
=> messy none

src/scales/schemes.js, test/output/colorSchemesOrdinal.html, test/scales/scales-test.js
The lighter color of the boolean color scales is difficult to see against a white background. This branch updates the default scale. See [this notebook](https://observablehq.com/@observablehq/boolean-colors-pr) to compare results.
=> Update boolean scheme9 scales

src/options.js, test/marks/dot-test.js
> TypeError: Cannot read properties of undefined (reading '0')
Plot.dot({ length: 1 }).plot()
The original use case was in a circlePacking layout where we would have Plot.dot({length:10}, circlePack({r: Math.random})).
However that use case is now solved by having the circlePack layout explicitly pass x: null, y: null. So maybe not worth the potential performance hit of checking each datum against null?
=> don't crash on Plot.dot({ length: 1 }).plot()

README.md, src/scales.js, test/scales/scales-test.js
=> Plot.scale(x) exposes bandwidth and step when applicable

src/legends.js, src/options.js, test/legends/legends-test.js, test/output/emptyLegend.svg, test/plots/empty-legend.js, test/plots/index.js
#756 changed the test used to determine whether or not a scale exists. This updates Plot.legend to match. Now `Plot.legend({color: {}})` throws an error because it does not consider the color scale to be defined (there is neither a type nor a domain). Supersedes #757.
=> fix for null scales

README.md, src/transforms/group.js, test/plots/athletes-bins-colors.js
We added x1, x2, y1, y2 in #613, but we should have x and y too for symmetry.
=> x and y reducers

src/style.js
I was thinking “fast divide by two”, not divide by four.
=> relax cardinality test

README.md, src/options.js, src/transforms/group.js, src/transforms/normalize.js, src/transforms/window.js, test/plots/aapl-monthly.js, test/plots/morley-boxplot.js, test/plots/movies-profit-by-genre.js
=> percentile reducers

src/axis.js, src/legends/swatches.js
=> null ticks, null tickFormat

src/marks/area.js
This allows e.g.
```js
Plot.area(timeSeries).plot()
```
Where `timeSeries` is an array of [date, number] tuples. This makes Plot.area consistent with Plot.line shorthand. Related #785.
=> tuple area shorthand

src/marks/rect.js
Same idea as #785, but for rects.
```js
Plot.rectY(numbers).plot()
```
=> indexed rect shorthand

src/plot.js
We need the emoji [variation selector](https://en.wikipedia.org/wiki/Variation_Selectors_(Unicode_block)) and, apparently, to avoid the system-ui font.
Before:
After:
=> fix emoji warning rendering in chrome

src/transforms/bin.js, test/output/binStrings.svg, test/output/binTimestamps.svg, test/output/stringBins.svg, test/plots/bin-strings.js, test/plots/bin-timestamps.js, test/plots/index.js
If the input channel is strings (or some other non-numeric type), we now coerce to a number. Example:
https://observablehq.com/d/71b0a051aff775f2
If the input channel is a typed array, we now also convert to a plain Array. This avoids an additional copy in d3.bin (since Array.isArray is false for typed arrays):
https://github.com/d3/d3-array/blob/2f28f41005de2fbb69e99439fabec5eb8bce26f0/src/bin.js#L16
And it also ensures that when we call coerceDate, that we produce an Array of Date instances (not possibly e.g. Float64Array of numbers).
https://github.com/observablehq/plot/blob/8af35be5fa27eefc9ab2227e44f1423724e09993/src/transforms/bin.js#L187
Fixes #789.
=> improve bin type coercion

src/format.js, src/marks/text.js, src/style.js
=> generic formatter for text channels

src/legends.js, src/plot.js, src/scales.js, src/scales/quantitative.js, src/style.js, src/transforms/bin.js, src/transforms/group.js, src/transforms/interval.js, src/transforms/map.js, src/transforms/normalize.js, src/transforms/select.js, src/transforms/stack.js, src/transforms/window.js
Before
```
Error: invalid reduce
```
After
```
Error: invalid reduce: avg
```
This should make it easier to track down errors.
=> add context for errors

src/legends/ramp.js, src/scales/quantitative.js, test/output/colorLegendQuantize.svg, test/output/colorLegendQuantizeDescending.svg, test/output/colorLegendQuantizeDescendingReversed.svg, test/output/colorLegendQuantizeReverse.svg, test/plots/legend-color.js, test/scales/scales-test.js
=> handle descending domain for quantize scales

src/marks/rect.js, src/transforms/interval.js, test/output/groupedRects.svg, test/plots/grouped-rects.js, test/plots/index.js
E.g. promotes *x* to *x1* and *x2* if the latter two are not specified.
~~I’m not sure why the aaplMonthly snapshot changed.~~ 🤔 Update: Fil figured it out.
=> trivial intervals for rect

README.md, src/index.js, src/options.js, src/transforms/bin.js, src/transforms/group.js, src/transforms/map.js, src/transforms/stack.js, src/transforms/tree.js
This helper is for constructing columns, not channels, even though typically those columns feed into channels. So I think the original Plot.column name is better, and we can still change it since we haven’t released it yet.
=> column, not channel

src/options.js
This follows on the issue described by @yurivish in https://github.com/observablehq/plot/pull/801#issuecomment-1119103573
I had also noted that Array.from is slow: https://observablehq.com/@fil/array-from-is-slower-than-expected
My understanding (after @mythmon showed me how to use a browser ;-) ) is that Array.from treats the data as an iterator, using the ->next method until completion, which means 1) it's necessarily slower than a tight loop and 2) it doesn't know how much memory to allocate (I speculate).
So when data is an array (it might not always be the case, iterators still have to be supported? though it seems that in all cases the data we pass to this function has already been arrayified), it might be worth using the faster path to populate it with indices.
Same story with type …
=> faster array manipulations

README.md, src/marks/dot.js, src/marks/image.js, src/marks/text.js, src/transforms/interval.js, test/output/athletesBirthdays.svg, test/output/seattlePrecipitationSum.svg, test/plots/athletes-birthdays.js, test/plots/index.js, test/plots/seattle-precipitation-sum.js
closes #611 
(not related to #597 which requires a very different kind of interval)
=> extend interval to dot and text marks

README.md, src/scales.js, src/scales/schemes.js, test/plots/gistemp-anomaly-moving.js, test/plots/gistemp-anomaly-transform.js, test/plots/gistemp-anomaly.js, test/plots/hadcrut-warming-stripes.js, test/plots/legend-color.js, test/plots/metro-inequality-change.js, test/plots/metro-unemployment-slope.js, test/plots/seattle-precipitation-rule.js, test/plots/seattle-temperature-band.js, test/plots/simpsons-ratings.js, test/plots/us-presidential-election-2020.js
I was thinking of cases like this, where a diverging scheme is specified, but the scale type is not specified and it defaults to _linear_.  It would be nice, when appropriate, to default to a _diverging_ scale instead so that it is symmetric around zero.
https://observablehq.com/@violetr/30daychartchallenge-day-13-correlation
I did this by checking for whether the _scheme_ is a diverging scheme, and whether a _pivot_ is specified or whether the _domain_ includes zero. The nice thing is that most of our tests that specify a diverging scale now merely need to specify a diverging scheme, though there were a couple tests that use a diverging scheme without a meaningful pivot (e.g., for temperature or IMDb rating where you want a diverging scheme simply for “low” and “high”).
=> default diverging based on scheme

src/channel.js, src/legends/ramp.js, src/options.js, src/plot.js, src/scales.js, src/scales/ordinal.js, src/scales/quantitative.js, src/transforms/interval.js
Continuation of #863: if we can use *array*.map or *array*.slice instead of Array.from, do so because it’s faster. Supposedly. I didn’t actually check so this could be premature optimization. But this was also relatively easy, so… 🤷.
=> avoid Array.from if possible

src/legends/ramp.js, test/output/carsHexbin.html, test/output/carsJitter.html, test/output/colorLegendDiverging.svg, test/output/colorLegendDivergingSqrt.svg, test/output/colorLegendImplicitLabel.svg, test/output/colorLegendLabelBoth.svg, test/output/colorLegendLabelLegend.svg, test/output/colorLegendLabelScale.svg, test/output/colorLegendMargins.svg, test/output/colorLegendOrdinalRampTickSize.svg, test/output/colorLegendQuantile.svg, test/output/colorLegendQuantileImplicit.svg, test/output/colorLegendQuantize.svg, test/output/colorLegendQuantizeDescending.svg, test/output/colorLegendQuantizeDescendingReversed.svg, test/output/colorLegendQuantizeRange.svg, test/output/colorLegendQuantizeReverse.svg, test/output/colorLegendThreshold.svg, test/output/colorLegendThresholdTickSize.svg, test/output/colorSchemesQuantitative.html, test/output/hexbinR.html, test/output/opacityLegend.svg, test/output/opacityLegendColor.svg, test/output/opacityLegendLinear.svg, test/output/opacityLegendLog.svg, test/output/opacityLegendRange.svg, test/output/opacityLegendSqrt.svg, test/output/simpsonsViews.html
The label for a ramp legend was erroneously inheriting the tabular-nums font-variant needed for axis ticks. This fixes it by making it a sibling rather than a child of the axis. I guess there’s the same bug with axis labels (which very rarely include numbers, so we didn’t notice).
Before
After
=> fix ramp legend font-variant

src/marks/delaunay.js, test/output/penguinVoronoi1D.svg, test/plots/index.js, test/plots/penguin-voronoi-1d.js
A complement to https://github.com/observablehq/plot/pull/930
the X and Y channels should be optional in all the voronoi marks—since d3-delaunay can handle collinear points (and it's not just for the sake of it: the resulting voronoi can be useful, as illustrated in the test case).
=> delaunay X and Y are optional

src/plot.js
Note: is it explicit enough, given that a common error is people who see the pattern `{facet: {data, x: "category"} }` and replace `data` with their own variable name, resulting in `{facet: {data2, x: "category"} }`?
another wording might be `the values to facet must be specified as the data property`, or something to that effect.
=> facet requires the data to be specified

README.md, src/marks/frame.js, test/output/frameCorners.svg, test/plots/frame-corners.js, test/plots/index.js
=> Plot.frame rounded corners

src/style.js, test/output/documentationLinks.svg, test/output/hrefFill.svg, test/plots/href-fill.js, test/plots/index.js
=> visited links color

src/scales/ordinal.js, test/scales/scales-test.js
(see https://github.com/observablehq/plot/pull/849#issuecomment-1105874552)
=> bail out if the inferred ordinal domain has more than 10k values

src/plot.js
**Reason for change**
While using Plot with external frameworks that have their own Dom implementations, it's possible the framework's Dom implementation doesn't support the newer Dom.append() method. This pull requests addresses the instance where plot uses Dom.append() to add a legend or a caption by using the Dom.appendChild() method.
**Testing with Salesforce's Lightning Web Component (LWC) framework**
I found this issue while trying to use Plot inside of Salesforce.com to create customized visualizations that Salesforce isn't capable of out of the box. I was able to successfully use Plot version 0.5.0 with no issues other than when I tried to add either a legend or a caption.
To test this PR, I built a dist after running tests and uploaded dist/plot.umd.js to Salesforce and added …
=> Change .append() to .appendChild()

src/plot.js
This allows different versions of Plot to be composed, e.g.: https://observablehq.com/d/2f8e482dc7cc105f
The duck test for Mark here is limited: it only tests for a render method, but it will crash downstream if the filter or initialize methods are not defined. We could test for those, too, or provide default implementations, but I figure this is fine for now.
=> use duck test for marks

src/legends/swatches.js, test/legends/legends-test.ts
=> swatches legend requires ordinal scale

README.md, src/axis.js, src/context.js, src/create.js, src/legends.js, src/legends/ramp.js, src/legends/swatches.js, src/marks/area.js, src/marks/arrow.js, src/marks/bar.js, src/marks/delaunay.js, src/marks/density.js, src/marks/dot.js, src/marks/frame.js, src/marks/hexgrid.js, src/marks/image.js, src/marks/line.js, src/marks/linearRegression.js, src/marks/link.js, src/marks/marker.js, src/marks/rect.js, src/marks/rule.js, src/marks/text.js, src/marks/tick.js, src/marks/vector.js, src/options.js, src/plot.js, src/style.js, test/document-test.js, test/legends/legends-test.ts
Fixes #848. This passes the **document** option to _mark_.render via a new _context_ argument.
=> document option

CHANGELOG.md, src/legends/swatches.js, src/scales.js, test/legends/legends-test.ts, test/output/colorLegendQuantileSwatches.html, test/plots/legend-color.js
Followup to #971 (#844). I think limiting swatches to ordinal color scales is probably too strict since threshold scales (including _quantile_ and _quantize_) can be represented _mostly_ accurately with swatches. E.g., swatches:
Versus ramp:
It is true that the lowest color is not displayed because the domain has one less element than the range. It is also true that the swatches are labeled ambiguously: you have to know that they represent the inclusive lower bound of a range. I think we could improve all this in the future, but that we shouldn’t throw an error for now.
=> allow threshold swatches

README.md
As far as I can tell, the `group` transform [accepts `"mode"` as an aggregation method](https://github.com/observablehq/plot/blob/08d3311f15dd628285c132997dee57b864e6aa58/src/transforms/group.js#L218).
This PR adds `"mode"` to the `README` in the list of aggregation methods for the `group` transform.
I'm not a statistics whiz, so I copied the `"mode"` entry from elsewhere with the assumption that it works the same.
=> Document "mode" for group transform

.mocharc.json, CONTRIBUTING.md, package.json
I’m not sure why this was added as part of TypeScript in #880, but having the spec in the .mocharc.json makes it harder to give Mocha a different spec from the command line. (It seems that Mocha ignores the spec on the command line in favor of the one in the .mocharc.json.) This changes makes it easier to run Mocha in watch mode on a custom spec, as shown in the CONTRIBUTING.md.
=> remove spec from .mocharc.json

src/plot.js, test/plots/gapminder-box-facet.js, test/plots/gapminder-box.js, test/plots/gapminder-dodge.js, test/plots/index.js
Save. (Not working, but getting closer.)
The tests are broken, they cover:
- gapminder-box.js : transforms (almost working, but some demultiplication of marks appears)
- gapminder-box-facet.js : faceted transforms (broken rects)
- gampinder-dodge.js : initializers (broken: it should not pile up all the dots from different time frames)
=> time & transforms

.gitignore, package.json, src/format.ts, tsconfig.json
This outputs the d.ts files. Once we've fully converted Plot to typescript we will add a "types" entry to package.json that references them, but not until then.
=> output d.ts files

README.md
ref. https://github.com/observablehq/plot/blob/977e0118dad0f05158dbc3c0cab5f92047f449fd/src/transforms/group.js#L174
see also https://talk.observablehq.com/t/plot-group-transform-behavior-default-channel-vs-array-of-objects/7259
=> document reduceTitle

scripts/readme-to-jsdoc.ts
I didn’t test thoroughly, but it seems to work for the simple cases like so:
```js
/** @jsdoc plot */
```
```js
/**
* @jsdoc plot
*/
```
```js
/**
* @jsdoc plot
* @param {Options=} options
*/
```
Ref. https://github.com/observablehq/plot/pull/1096#issuecomment-1289082896
=> allow jsdoc type declarations

src/dimensions.js, src/projection.js, test/output/downloadsOrdinal.svg, test/output/ibmTrading.svg, test/plots/dot-sort.js
See https://observablehq.com/@observablehq/plot-band-scale-bug-1045
fixes #1045
Note: this is the least disruptive I could do; but it becomes a bit complicated to understand, as we need to compute what the default margins would have been, and add the difference.
(includes #1059, in order to pass CI)
See also #837
=> autoHeight factors in the auto and manual margins. 

README.md, src/projection.js
as part of #1125 and an addition to #1124: specifying a projection inset, in pixels, will fit the projection slightly towards the interior of the frame
this is not urgent and should be thought about with the rest of #1125
=> projection.inset

src/marks/dot.js, src/marks/geo.js
0 is accepted, as it doesn't result in an error for dots and images, and may be useful for geo marks.
fixes #1145
=> the dot or geo mark is empty if given a constant negative r

src/projection.js
Avoids exposing the aspect ratio in the public API; is this legal, though?
=> symbol ratio

src/channel.js, src/plot.js, test/output/athletesBoxingHeight.svg, test/plots/athletes-boxing-height.js, test/plots/index.js
closes #1176
Notes:
* is there a way to make sure transform is only called for the fx fy scale?
* I spent more time looking up the non-standard country codes from the olympians dataset than fixing the bug.
=> apply fx/fy transform option

src/marks/contour.js, src/marks/raster.js, test/plots/raster-vapor.js
Throws an error in this case:
```js
Plot.raster({width: volcano.width, height: volcano.height, fill: volcano.values}).plot()
```
Instead you should say:
```js
Plot.raster(volcano.values, {width: volcano.width, height: volcano.height}).plot()
```
The dense grid in screen coordinates is only possible when _fill_ is specified as a function (and sampled by inverting the _x_ and _y_ scales).
=> sampler requires a function

README.md, src/axes.js, src/axis.js, src/legends/ramp.js, src/legends/swatches.js, src/options.js, src/time.js, src/transforms/bin.js, src/transforms/interval.js, test/plots/aapl-volume-rect.js, test/plots/availability.js, test/plots/bin-timestamps.js, test/plots/crimean-war-overlapped.js, test/plots/crimean-war-stacked.js, test/plots/downloads-ordinal.js, test/plots/downloads.js, test/plots/ibm-trading.js, test/plots/industry-unemployment-track.js, test/plots/polylinear.js, test/plots/seattle-precipitation-sum.js, test/plots/sf-covid-deaths.js, test/plots/stargazers-binned.js, test/plots/stargazers-hourly-group.js, test/plots/stargazers-hourly.js, test/plots/untyped-date-bin.js, test/plots/yearly-requests-dot.js
Fixes #307. This is going to conflict with #1197, so I could merge the two if desired.
=> named time intervals

package.json, src/index.js, src/mark.js, src/marks/area.js, src/marks/arrow.js, src/marks/bar.js, src/marks/delaunay.js, src/marks/density.js, src/marks/dot.js, src/marks/frame.js, src/marks/geo.js, src/marks/hexgrid.js, src/marks/image.js, src/marks/line.js, src/marks/linearRegression.js, src/marks/link.js, src/marks/raster.js, src/marks/rect.js, src/marks/rule.js, src/marks/text.js, src/marks/tick.js, src/marks/vector.js, src/plot.js
This is broken out of #1197 so that we can minimize the drift from main and make it easier to keep the axis mark branch up-to-date with changes. There are no functional changes in this PR; just moving code (and tweaking how we handle null marks, but the difference should not be externally visible).
=> move Mark class

src/facet.js, test/output/autoDotFacet2.svg, test/plots/autoplot.js
fixes https://github.com/observablehq/plot/issues/1254
When a facet is empty, we could return undefined and repeat the test on f.empty after the `??`. However it felt more logical to return false, as we have “settled the matter”, so to speak.
https://github.com/observablehq/plot/blob/a7f76ef66fc7f7e6d6727e935ffdd370e69013b8/src/plot.js#L257
=> avoid spurious facet anchor

src/marks/delaunay.js, test/output/penguinVoronoi1D.svg, test/plots/penguin-voronoi-1d.js
Fixes #1258, affecting the **target**, **mixBlendMode**, and **opacity** options.
=> fix voronoi mark styles

README.md, src/marks/image.js, test/output/imagePixelated.svg, test/plots/image-rendering.js, test/plots/index.js
=> Plot.image supports imageRendering

src/marks/auto.js, test/output/autoBarMeanZero.svg, test/output/autoLineHistogram.svg, test/output/autoLineMean.svg, test/output/autoLineMeanColor.svg, test/output/autoLineMeanZero.svg, test/plots/autoplot.js
=> only default to bar for x or y is zeroed

src/marks/auto.js, test/output/autoBarMode.svg, test/plots/autoplot.js
Fixes another bug where we assumed that reducers produce quantitative values. In some cases, _e.g._ with the _mode_ reducer, reducing preserves the input value type. For example:
```js
Plot.auto(penguins, {x: "island", y: {value: "species", reduce: "mode"}, mark: "bar"}).plot()
```
Before, barY is wrongly chosen, resulting in a degenerate plot:
After, cell is correctly chosen, since both _x_ and _y_ are ordinal:
=> fix bars with maybe-ordinal reducers

.eslintrc.json, src/scales.js, test/output/bigint1.svg, test/output/bigint2.svg, test/output/bigintLog.svg, test/output/bigintOrdinal.html, test/plots/bigint.js, test/plots/index.js
closes #1278
@llimllib see if you can break this branch by passing bigints to unsuspected places (a build is available at https://observablehq.com/@observablehq/plot-bigint-1278 )… note that we're supporting bigints only as channel values, not as options (_e.g._ we don't try to support `inset: 1n` or `margin: 10n`).
As I was researching all the places where we coerce values to a number, I realized that this line is probably redundant, as we enter inferLogDomain only with already-coerced channels:
https://github.com/observablehq/plot/blob/d8378f088fa39d611f3219992ad5e452418765b6/src/scales/quantitative.js#L293
=> minimal support for bigint

src/marks/auto.js, test/output/autoLineMeanThresholds.svg, test/plots/autoplot.js
Related #1261 #1252, allows _x_- and _y_-specific options to be passed through when binning. This is primarily useful for control over thresholds. Given the ambiguities raised in https://github.com/observablehq/plot/pull/1261#pullrequestreview-1285786800, I’m only doing this for the bin transform; for example you still can’t use scale overrides added in #1247. (I think that’s okay because scale overrides are fairly esoteric, and you can switch to a concrete mark type if needed.)
=> auto bin options

src/scales/quantitative.js
It is redundant since in the case of a log scale, the values have already been coerced to a Float64Array by https://github.com/observablehq/plot/blob/d8378f088fa39d611f3219992ad5e452418765b6/src/scales.js#L306
(It's not a huge deal since we call it maybe just once or twice… anyway. Researched with #1279.)
=> remove coercion in inferLogDomain

README.md, src/facet.js, test/output/futureSplom.svg, test/plots/frame.js
This can be useful, for example with a SPLOM (not ready yet); see also https://observablehq.com/@heman/brush
Otherwise I have to do a weird trick:
>     Plot.axisFx({ label: null, y: (d, i) => -3.35 * (i + 0.05) }),
https://observablehq.com/@observablehq/positioning-facet-names-1287
TODO:
=> facetAnchor: empty

src/plot.js
=> avoid a crash on facet: exclude on a non-faceted mark

src/scales/ordinal.js, src/scales/quantitative.js, test/scales/scales-test.js
Includes the scale name in errors for easier debugging.
I also rewrote the `isOrdered` helper to iterate directly, instead of materializing all the pairs using d3.pairs and then testing with _array_.every. I think it’s cleaner this way, and slightly faster, not that it matters.
=> include scale name in error

README.md
closes #1293
while its main usage is internal, facet: super can be used to add a radius legend or a title
=> document facet: super

src/channel.js, src/mark.js, test/output/athletesSortFacet.svg, test/plots/athletes-sort.js
=> fix facet channel sort with transform

src/interval.d.ts, src/marks/axis.d.ts, src/marks/axis.js, src/options.js, src/scales.d.ts, src/scales/ordinal.js, src/scales/quantitative.js, src/transforms/bin.d.ts, src/transforms/bin.js, test/plots/electricity-demand.ts
Fixes #1331.
Fixes #1240.
(Also fixes #1333 as a duplicate of #1240)
=> strict range interval, nice interval

src/marks/auto.js, test/output/autoRuleZero.svg, test/plots/autoplot.ts
[Mike writes:](https://github.com/observablehq/plot/issues/1340#issuecomment-1469302368)
>The mark-based zero check is also forgetting about rule. This should have a y = 0 rule like rect does.  
Now it does! 
|Before|After|
|-|-|
|![autoRuleZero-changed](https://user-images.githubusercontent.com/841829/225350516-f83ec6ad-7a03-4110-a527-27699f7d2269.svg)|![autoRuleZero](https://user-images.githubusercontent.com/841829/225350369-4280f509-09ab-4a17-b96f-5e67f3793cd8.svg)|
```js
Plot.auto(olympians, {x: "date_of_birth", y: {value: "height", reduce: "mean"}, mark: "rule"}).plot()
```
A couple notes:
barY or areaY or rectY or… ruleX? Yes; ruleY would be the one parallel to the y baseline, and can make sense without any zero baseline; ruleX is the one orthogonal to the baseline, which has to …
=> Auto mark: zero baseline default for rules

src/style.js, test/style-test.js
=> allow mixed-case class names

README.md, src/transforms/window.d.ts
remarks:
* *k* is not optional
* *shift* is deprecated
* added the *strict* option to README
for #1343
=> document window

src/transforms/select.d.ts
for #1343 
note that we don't cover the case where symbol is constant, but we try to select it with `select({symbol: "min"})`; this should be red:
=> document select

src/transforms/normalize.d.ts
for #1343
lots of repetitions, but looks ok?
=> document normalize

src/marks/vector.d.ts
For #1343 
First mark to be documented with its default tuples, and X, Y variants. Once we agree on the wording, it will be used as a template for all similar marks.
I tried to make a simple sentence describing the mark with its (main) options in bold—not sure if this will work for all marks.
=> document vector

src/transforms/hexbin.d.ts
for #1343 
(do we need to explain that it's an initializer?)
=> document hexbin

loader.js, package.json, yarn.lock
Everything seems to work as-is. Just a small breaking change in @esbuild-kit/core-utils needed to upgrade for Mocha tests.
=> TypeScript 5.0.2

README.md, src/channel.d.ts, src/interval.d.ts, src/marks/vector.d.ts, src/reducer.d.ts, src/transforms/bin.d.ts, src/transforms/group.d.ts, src/transforms/hexbin.d.ts, src/transforms/map.d.ts, src/transforms/normalize.d.ts, src/transforms/normalize.js, src/transforms/stack.d.ts, src/transforms/window.d.ts, test/plots/function-contour.ts
=> document group & bin

src/transforms/dodge.d.ts, src/transforms/window.d.ts
for #1343 
Note: I've separated the options for dodgeX and dodgeY.
=> document dodge

src/transforms/centroid.d.ts
=> document centroid

src/plot.d.ts, src/projection.d.ts
For #1343 
Note: **precision** appeared to be missing.
=> document projection

README.md, src/mark.d.ts
=> document mark

src/marks/area.d.ts
for #1343 
very similar to Plot.line (#1401), but I realized the README glosses over the variable aesthetics for this mark (I've added them here for the jsdocs).
=> document area

src/marks/area.d.ts, src/marks/line.d.ts
=> document line

src/marks/dot.d.ts
=> document dot and symbol

README.md
note: there are tests in aapl-close.ts.
closes #1372
=> document grid: string etc.

src/marks/rule.d.ts, src/marks/tick.d.ts
=> document rule

src/marks/area.d.ts, src/marks/bar.d.ts, src/marks/frame.d.ts, src/marks/rule.d.ts
=> document barX barY

src/marks/area.d.ts, src/marks/bar.d.ts, src/marks/rect.d.ts, src/marks/rule.d.ts, src/marks/tick.d.ts
=> document rect

.github/workflows/node.js.yml
We’re using some old deprecated actions which use Node 12. Found [here](https://github.com/observablehq/plot/actions/runs/4567228301).
Ref. https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> upgrade actions

src/marks/bar.d.ts, src/marks/cell.d.ts, src/marks/frame.d.ts, src/marks/rect.d.ts
=> document cell

src/marks/geo.d.ts
=> document geo

src/marks/link.d.ts
for #1343 
note: more precise jsdoc for the **curve** option
todo:
=> document link

README.md, src/inset.d.ts, src/marks/arrow.d.ts, src/marks/link.d.ts
for #1343 
Also fixed a mix-up in README
=> document arrow

src/marks/dot.d.ts, src/marks/image.d.ts
=> document image

src/marks/text.d.ts, test/plots/text-overflow.ts
=> document text

src/marks/linearRegression.d.ts
=> document linearRegression

README.md, src/marks/box.d.ts, src/marks/box.js
for #1343
Say what happens with *stroke*/*z*? In my view it's technically working but hard to see if you don't add fillOpacity, so maybe it needs a bit more work.
=> document box

README.md, src/marks/contour.d.ts, src/marks/raster.d.ts, src/transforms/bin.d.ts
for #1343
Note: added *interval* in the raster options, and explicitly discarded the raster interval option from the type, to add the contour interval option instead—not sure it's needed, but it felt like the right thing to do.
=> document raster and contour

README.md, src/marks/axis.d.ts, src/scales.d.ts
=> document axis

README.md, src/legends.d.ts, src/legends/ramp.js, src/legends/swatches.js, test/output/colorLegendOpacity.html, test/output/colorLegendOpacityOrdinalRamp.svg, test/output/colorLegendOpacityRamp.svg, test/output/symbolLegendOpacityColor.html, test/output/symbolLegendOpacityFill.html, test/output/symbolLegendOpacityStroke.html, test/plots/legend-color.ts, test/plots/legend-symbol.ts
Note: I used **fillOpacity** and not **opacity**, for consistency with the *symbol* legends.
closes #1356
=> support for fillOpacity in swatch and ramp color legends

src/plot.js
when ~~both the~~ (EDIT:) **any of** data length and facet data length are undefined, suppress the warning
fixes #1429
Note: I initially added arquero as a devDependency and @juba’s penguins test, but removed it as I felt it adds too much cruft. The test was:
```ts
import * as Plot from "@observablehq/plot";
import * as d3 from "d3";
import * as aq from "arquero";
export async function penguinArqueroFacet() {
const data = await d3.csv<any>("data/penguins.csv", d3.autoType);
const penguins = aq.from(data).toArrow();
return Plot.plot({
facet: {data: penguins, x: "island"},
marks: [Plot.dot(penguins, {x: "culmen_depth_mm", y: "body_mass_g"}), Plot.frame()]
});
}
```
=> fix for 1429

src/marks/density.js
The density mark was erroneously importing create from d3 rather than context.js, and hence was always creating the SVG G element using the global document, ignoring the context. This fixes server-side rendering of the density mark. (I also ran VS Code’s Organize Imports command to keep the imports sorted.)
=> fix create import

src/style.js
We currently assume the opposite, but given that high-pixel-density screens are definitely the norm, this seems like the better default. This is desirable for server-side rendering of Plots to avoid a half-pixel shift on the client, assuming the client has a high-pixel-density screen.
Note that to avoid re-generating all the test snapshots, I’ve left the default as-is for Mocha (by testing `typeof it`). In a follow-up commit we can remove this exemption and update the snapshots.
=> assume high pixel density when headless

src/context.d.ts, src/context.js, src/legends.js, src/plot.js
This is needed for deterministic server-side rendering of legends.
=> propagate className option to legends

src/plot.js
During server-side rendering, the global `Node` may not be available. And if the **document** option is used, we don’t want to use the global `Node` in any case. So this switches to a duck test using *node*.ownerDocument instead, which should be sufficiently unambiguous.
=> avoid instanceof Node

src/marks/axis.js, test/output/axisLabelHref.svg, test/output/axisLabelVaryingFill.svg, test/plots/axis-labels.ts
Fixes #1453. The problem is that the **href** option was being passed to the axis label mark, too, which presumably caused the mark to be filtered out? I think we might need a more general solution for preventing channels on the singular axis label mark…
=> fix #1453; axis label and href

src/marks/delaunay.js
This avoids an unnecessary querySelectorAll and compareDocumentPosition call when we know the selection is empty.
=> enter-append instead of join

docs/.vitepress/theme/custom.css, docs/components/PlotRender.js, docs/features/plots.md
We still have the lazy plot scrolling problem, but how is this for linking to an option without an explicit section?
=> #aspectratio

src/marks/axis.js, src/time.js, test/output/internFacetDate.svg, test/output/yearlyRequestsDot.svg, test/plots/yearly-requests-dot.ts
If an ordinal scale has a yearly interval, use the appropriate %Y tick format by default, instead of isoformat which adds a trailing -01-01. Ref. https://github.com/observablehq/plot/issues/768#issuecomment-1528924713.
=> detect ordinal year intervals

src/marks/tooltip.js
test: https://observablehq.com/@fil/tt-tests
(code is a bit meh)
=> mobile tooltip on tap

src/mark.js, src/marks/tip.js, src/options.js
Currently if you declare an extra channel, say **info** to show the corresponding field in the olympians dataset, you get a default filter that drops most of the points.
This changes it so that such extra unscaled channels do not get the default `defined` filter. (You can still specifying the **filter** option explicitly if desired.)
This also changes the tip mark to hide unscaled, undefined channel values, avoiding many nulls for sparse fields.
However, scaled channels still show nulls, which is good for confirming missing data.
Perhaps in the future there will be an option to control explicitly whether the tip displays null values… but this seems like a better default.
=> don’t filter extra unscaled channels by default

src/mark.d.ts, src/mark.js, src/marks/rule.js, src/plot.js, src/transforms/bin.js, src/transforms/dodge.js, src/transforms/stack.js, test/plots/tip.ts
This adds a **tip** option for generating a tip mark + pointer interaction from a given mark. It can be set to _x_, _y_, or _xy_ for pointerX, pointerY, or pointer respectively, or to true in which case the default orientation is used (such as _x_ in conjunction with implicit stackY). When plotting, these marks are created implemented and drawn atop all other marks.
In the future, perhaps the **tip** option could be specified as an object allowing additional tip options such as **anchor**.
=> tip option

src/marks/arrow.js, src/marks/box.js, src/marks/cell.js, src/marks/density.js, src/marks/dot.js, src/marks/image.js, src/marks/line.js, src/marks/linearRegression.js, src/marks/link.js, src/marks/text.js, src/marks/tick.js, src/marks/tree.js, src/transforms/bin.js, src/transforms/map.js, src/transforms/tree.js
This restores function parameter destructuring that was removed in 8065e59af569be9e0c37ec6686e895fa4e9a4471 (#1034); now that we have separate TypeScript declaration files, there’s no obligation that the JavaScript implementation match the public interfaces in TypeScript, so we can write the implementation as we desire.
There are no functional changes here.
=> restore inline destructuring

src/marks/auto.js, test/marks/auto-test.js
This applies apply the same logic as for area to decide between lineX and lineY, but, when not sure, defaults to line (whereas area defaults to areaY).
closes #1547
=> prefer lineX when Y is monotonic, lineY when X is monotonic, for better tooltips

src/marks/auto.js, test/marks/auto-test.js
The auto was always choosing rectX or rectY, but sometimes we want rect because it has more appropriate pointing behavior. Ref. https://twitter.com/angiehjort/status/1658474295788724229
=> auto chose rect

src/channel.js, test/output/opacityDotsFillUnscaled.svg, test/output/opacityDotsStrokeUnscaled.svg, test/output/opacityDotsUnscaled.svg, test/plots/index.ts, test/plots/opacity.ts
I've added three tests with the same visual result; in main, the _opacityDotsUnscaled_ test is scaled and results in darker dots.
fixes #1570
=> the object opacity channel should opt-out of the opacity scale too

src/scales.js, test/output/shorthandCellCategorical.svg, test/plots/raster-walmart.ts
Complement to #1567: we do the scheme test _after_ the domain (or values) have been tested. Fixes the regressions with diverging schemes and temporal scales.
=> implicit categorical color scale

test/output/carsParcoords.svg, test/plots/cars-parcoords.ts
We must apply the normalization over the _whole extent of the data_ in both marks (line and "axis"); the previous version was normalizing the axes on the ticks only, resulting in misalignment between the values and the ticks.
=> Fix the parcoords chart.

src/interactions/pointer.js, src/mark.d.ts, src/mark.js, src/plot.js
Rather than expecting the render transform to call mark.render, this passes a *next* function to the render transform. This would allow us to compose render transforms, potentially. (That wouldn’t be possible if the render transform is expected to call this.render internally.)
=> composable render transforms

src/mark.js, src/marks/tip.js
Fixes #1580. Also fixes `tip: false` which should be the same as `tip: null`.
=> no tip for tip

docs/marks/raster.md
=> fixes to the documentation

docs/transforms/tree.md, src/marks/tree.d.ts, src/marks/tree.js, src/transforms/tree.d.ts, src/transforms/tree.js, test/output/flareIndent.svg
Ref. https://github.com/observablehq/plot/pull/1610#pullrequestreview-1436974604
=> treeFilter option

src/scales/diverging.js, src/scales/quantitative.js, test/output/colorMisalignedDivergingDomain.html, test/output/colorMisalignedLinearDomain.html, test/output/colorMisalignedLinearDomainReverse.html, test/output/colorMisalignedLinearRange.html, test/output/colorMisalignedLinearRangeReverse.html, test/plots/color-misaligned.ts, test/plots/index.ts, test/scales/scales-test.js
=> fix misaligned range

src/channel.d.ts, src/plot.js, test/output/tipTransform.html, test/plots/tip.ts
when using a derived mark (such as a tip), a scale transform was applied twice
=> fix: avoid double application of a scale transform 

test/output/tipDotX.svg, test/plots/tip.ts
This initially surprised me, but now I think it might be desirable/acceptable: if the mark has primitive data, we consider it to be “textual”, and hence default the **title** channel to *identity*. And hence the tip displays the data rather than the channels. If the mark has primitive data, then maybe it’s unlikely that the channels would show anything else interesting? So this might be a reasonable default. But I can’t think of a way to opt-out of this behavior and show all channels, either, since the **title** option isn’t visible to the derived tip—it can only see the data and the channels…
=> test tip for primitive data

src/style.js, test/output/pairsArea.svg, test/plots/index.ts, test/plots/pairs.ts
The intent of this “high cardinality” warning (as specified [here](https://github.com/observablehq/plot/pull/761#issuecomment-1043121845)) is the following: when a mark only¹ makes sense with grouping—currently area, line, linearRegression and density—, we want to warn when the number of groups (G.size) is higher than the smallest possible number of _meaningful_ groups, which is I.length >> 1 (obtained when the groups are pairs).
However when there is an odd number of elements, having 1 element that falls out is to be expected and should not invalidate the chart.
Closes #1667
¹ It's not a hard rule: the areaY mark with a stroke, the lineY mark with a marker, and the density mark tolerate single points. But these are not the default usage.
=> Refine “high cardinality” warning

src/marks/auto.js, test/output/autoBarNoReducer.svg, test/plots/autoplot.ts
If there's no reducer, the rects will have no extent, so we should treat numbers as ordinal. Fixes https://github.com/observablehq/plot/issues/1672. This lets us get to e.g. the Simpsons ratings heatmap:
```js
Plot.auto(simpsons, {x: "season", y: "number_in_season", color: "imdb_rating", mark: "bar"}).plot()
```
This will never be chosen unless `mark: "bar"` is passed, because of `isZeroReducer(xReduce) || isZeroReducer(yReduce) || colorReduce != null ? "bar"` above.
=> Auto: given bar, use cell over rect when no reducer

docs/.vitepress/theme/custom.css
the issue was affecting only safari, e.g. on /plot/transforms/window
thanks to @mootari for the fix
before
after
=> fixes an alignment issue for radio buttons

docs/.vitepress/theme/custom.css, docs/what-is-plot.md
from the d3 website: https://github.com/d3/d3/commit/fbf24bb271759bb8297722377fb767d5aa12d78a and https://github.com/d3/d3/commit/9f88f025e8fc5903b70ec80a105606508056d0bb
=> documentation tree

docs/features/scales.md
Probably not needed now that #1285 was closed by #1718
=> Remove tip from scales.md

docs/transforms/stack.md
The plot is built with stackY2, but the code in the docs shows stackY
=> Fix typo in stack.md

src/marks/tree.js, test/output/greekGodsTip.svg, test/plots/greek-gods.ts
I pondered a bit what happens when dotDot is falsy: we could then add the tip option on the text mark, but this would in turn create more complexity. Decided to keep it simple.
=> closes #1723

src/marks/arrow.d.ts, src/marks/arrow.js, test/plots/collatz.ts, test/plots/miserables.ts
I prefer to encapsulate the logic in a function. This also makes it easier for a user to extend with custom logic — even if we don’t chose to expose that extensibility yet.
=> functional sweep

docs/.vitepress/theme/CustomLayout.vue, docs/.vitepress/theme/ObservablePromo.vue, docs/.vitepress/theme/index.ts
=> observable promo

src/interactions/pointer.js
Because we're checking for strict inequality of the distance to the best facet, it can happen that we display 2 tips if the pointer is exactly at the same distance from two target points in different facets. This fixes this corner case, by retaining only the first point in case of strict equality.
I've seen it happen once, by chance, when I was playing with https://observablehq.com/d/a03f70ae5c5962c4 — so I'm sure it can happen in the wild, but it's difficult to reproduce: you need an environment where the pointer has integer coordinates (this depends on the browser, I think?), and the two targets have integer coordinates (e.g., using the round: true option on x — it's on by default on fx).
=> fix a corner case where pointer interaction generates two points

docs/.vitepress/config.ts, docs/marks/bollinger.md, docs/marks/rule.md, src/index.d.ts, src/index.js, src/marks/bollinger.d.ts, src/marks/bollinger.js, test/plots/aapl-bollinger.ts
=> bollinger mark & transform

docs/features/plots.md, src/context.d.ts, src/context.js, src/mark.js, src/marks/axis.js, src/marks/frame.js, src/plot.d.ts, src/style.js, test/plots/band-clip.ts
Adds a top-level **clip** option that is inherited by marks that don’t specify the **clip** option explicitly. The axis mark and frame mark deviate from this rule; their **clip** option defaults to false instead of undefined. This makes it easier to turn on clipping for multiple marks, e.g. for the candlestick example in the other branch.
=> top-level clip option

src/format.d.ts, src/marks/text.d.ts, src/plot.d.ts, src/scales.d.ts, src/transforms/stack.d.ts, src/transforms/window.d.ts
Normalize to using numbered links everywhere. Change a few http to https. 
Note that this changes the aspect of one element (_locale_), which goes from "paragraph" to "inline" mode:
(Also, when the URL is long, we get bad reflows when using option-Q in VS Code.)
=> normalize links in JSDoc comments

src/format.d.ts
(as suggested by https://github.com/observablehq/plot/pull/1794#discussion_r1287786741; note that the second line is still in the ugly "paragraph" mode in VSCode, even though it's shorter that the first line 🤷
=> avoid repetition of format options

src/transforms/stack.js, test/output/pointerLinkedRectInterval.svg, test/plots/index.ts, test/plots/pointer-linked.ts
Originally, I tried this:
```js
Plot.rectY(
series,
Plot.pointerX({
x: "time",
y: null,
interval: {
floor: (x) => Math.floor(x) - 0.5,
offset: (x) => x + 1
}
})
),
```
This leads to a vague error:
```
TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
```
The error can be reproduced as:
```js
Plot.valueof([], null, Float64Array)
```
In the context of valueof, I think the error is okay: if you specify an array type then (I guess?) the _value_ argument must not be null. But in the broader context of the stack transform, the stackY transform requires that _y_ not be null since it will subsequently dereference those values even if we allowed valueof to return null here. So I think it’s better that we abort early with a more helpful error message.
Eventually …
=> better error message for missing stack value

src/marks/auto.js, test/output/autoBarTimeSeries.svg, test/output/autoBarTimeSeriesReduce.svg, test/plots/autoplot.ts
Fixes #1800. The logic is quite complicated — but I think it helped to start by looking at the reducers, since that determines whether there is a bin or group transform.
=> refine auto bar mark determination

src/scales/ordinal.js, test/scales/scales-test.js
=> expose a deduplicated ordinal domain

docs/.vitepress/config.ts, docs/components/PlotRender.js, package.json, src/plot.js, yarn.lock
- fix a crash with docs:build and figure.append / el.append
- upgrade vitepress to 1.0.0-rc.4 (https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md)
- generate a sitemap at ./docs/.vitepress/dist/sitemap.xml (available with the vitepress update, see https://github.com/vuejs/vitepress/pull/2691; documentation: https://vitepress.dev/guide/sitemap-generation#sitemap-generation)
Re: the crash, I don't understand why it doesn't seem to happen in production.  When I call `yarn docs:build` with the current main branch, I get dozens of errors:
```
✓ building client + server bundles...
⠹ rendering pages...TypeError: Function.prototype.apply was called on undefined, which is a undefined and not a function
at Module.plot (file:///Users/fil/Sites/plot/docs/.vitepress/.temp/plot.c0318f47.js:5839:1 …
```
=> update vitepress, fix a build crash, add a sitemap

docs/.vitepress/theme/CustomLayout.vue, docs/.vitepress/theme/ExamplesGrid.vue, docs/.vitepress/theme/gallery.data.js, package.json, yarn.lock
Same as d3js.org, but I added `?intent=fork` here because it isn’t baked into the paths in the Plot gallery. I think we should probably bake them in explicitly in the Plot gallery so that we can selectively remove the fork banner when appropriate, but this is okay for now.
=> add examples grid

src/transforms/bin.js, test/output/binFillFirstEmpty.html, test/output/integerIntervalArea.html, test/output/integerIntervalAreaZ.html, test/plots/bin-fill-first-empty.ts, test/plots/index.ts, test/plots/integer-interval.ts
For z, stroke and fill. Previously b[0] was undefined, so a spurious undefined value was potentially added to GZ, GF or GS.
cc @yurivish 
closes #1775
=> Empty bins fall back on the first element of their group

src/mark.js, test/plots/tip-format.ts
Related #1734 #1831. Continuation of #1823.
=> channel label override

src/options.js, test/output/varColor.svg, test/output/varColor2.svg, test/output/varColorP3.svg, test/plots/index.ts, test/plots/var-color.ts
Ref. https://www.w3.org/TR/css-color-5/
Allows a variety of new ways of specifying colors, including mixing colors:
```
color-mix(in lch, purple 50%, plum 50%)
```
And relative colors:
```
lch(from currentColor calc(1 - l) c h)
```
Though, I can’t really seem to get the latter to work, so probably we should leave this as a draft until it works.
Fixes #1851.
=> allow CSS Color Module Level 5

docs/marks/tip.md
* [tip format](https://observablehq.com/@observablehq/plot-tip-format) introduced in v0.6.11
=> additional documentation fork link

package.json, src/marks/axis.js, src/time.js, test/output/timeAxisLocal.svg, test/plots/time-axis.ts
=> fix local time

docs/data/api.data.ts, src/marks/bollinger.d.ts
The bollinger map method is currently erroneously referred to as the “bollinger window mark” in the API reference (since the name is automatically inferred from the BollingerWindowOptions interface which lives in the marks folder). This corrects it to be “bollinger map method” to be consistent with the other docs.
=> fix bollinger reference

src/marks/tip.js, test/output/tipLongText.svg, test/plots/tip.ts
(bug reported and fixed by @mootari)
| before | after |
| --- | --- |
| <img width="416" alt="Capture d’écran 2023-11-01 à 14 36 43" src="https://github.com/observablehq/plot/assets/7001/1a33c70a-b00f-4a7a-aced-5f5a8cfac15b"> | ![Capture d’écran 2023-11-01 à 14 33 43](https://github.com/observablehq/plot/assets/7001/1ed6316a-f928-4e27-9e49-e2da3c4f20fb) |
=> only truncate the long visible text, not the title

docs/marks/bar.md, docs/marks/cell.md, docs/marks/rect.md, src/marks/rect.js, src/transforms/interval.js, test/output/groupedRects.svg, test/output/rectBandX.svg, test/output/rectBandX1.svg, test/output/rectBandY.svg, test/output/rectPointX1.svg, test/plots/rect-band.ts
=> rect support for band scales

src/transforms/dodge.d.ts, src/transforms/normalize.d.ts, src/transforms/stack.d.ts, src/transforms/window.d.ts
This fixes a TypeScript type inference bug in a case like this:
```js
Plot.plot({
marks: [
Plot.differenceY(
stocks,
Plot.normalizeY(
Plot.groupX(
{y1: Plot.find((d) => d.Symbol === "GOOG"), y2: Plot.find((d) => d.Symbol === "AAPL")},
{x: "Date", y: "Close", curve: "cardinal", tension: 0.1}
)
)
)
]
})
```
Previously, TypeScript would assume that the normalizeY transform was being passed a single argument of _basis_; now it correctly assumes that it is being passed a single argument of _options_.
=> fix overload precedence

docs/.vitepress/theme/index.ts
Send first-party analytics using common library.
=> Use reusable Observable analytics client

src/scales/quantitative.js, test/output/zeroNegativeDegenerateY.svg, test/output/zeroNegativeY.svg, test/output/zeroPositiveDegenerateY.svg, test/output/zeroPositiveY.svg, test/plots/index.ts, test/plots/zero.ts
=> fix inversion when collapsed domain

docs/.vitepress/theme/index.ts
This actually isn't correct either, but restores the previous behavior that it seems to rely on. The current code watches router.route, but after an async import which means it actually misses the first actual page load and doesn't fire anything. A subsequent navigation counts as the first pageLoad.
I'll have a better fix soon, but wanted to restore the previous behavior in the meantime.
=> Patch analytics pageLoad event for now

docs/.vitepress/theme/index.ts
Follow up to #2043.
Synchronously watch for route changes and send pageLoad or routeChanged events. Doesn't rely on the automatic pageLoad event anymore from the analytics client.
Tested locally and verified pageLoad was being sent on initial load and routeChanged sent on client side navigation.
=> Send our own pageLoad, routeChanged events

docs/transforms/group.md
For `find` heading, custom anchors should be specified after `<VersionBadge />`?
| Before    | After |
| -------- | ------- |
| <img width="1435" alt="iShot_2024-04-22_14 33 52" src="https://github.com/observablehq/plot/assets/49330279/c126632a-69de-4b60-b427-a0cc9052f220">  | <img width="1432" alt="iShot_2024-04-22_14 34 13" src="https://github.com/observablehq/plot/assets/49330279/c92e8c14-de49-4259-8ddb-7f4ff4f3d066">   |
=> Update group.md to fix display error of find heading

test/jsdom.js
Our tests do not need global.navigator, which is now present on node (https://nodejs.org/en/blog/announcements/v21-release-announce#navigator-object-integration). And, since it's only a getter, upgrading node was breaking the tests with:
> TypeError: Cannot set property navigator of #<Object> which has only a getter
Note: if we needed to use jsdom.window’s navigator, we could remove node’s version by applying the following snippet: https://github.com/nodejs/node/pull/50310/files
=> Fix testing under node >= v21

docs/marks/tip.md, src/marks/tip.d.ts, src/marks/tip.js, src/scales.d.ts, test/output/tipFormatTitleFormat.svg, test/output/tipFormatTitleFormatFunction.svg, test/output/tipFormatTitleFormatShorthand.svg, test/plots/tip-format.ts
=> tip title format

docs/features/formats.md, src/format.d.ts, src/index.js, src/marks/axis.js, test/marks/format-test.js, test/output/logTickFormatFunction.svg, test/output/logTickFormatFunctionSv.svg, test/plot.js, test/plots/index.ts, test/plots/log-tick-format.ts
Fixes #2077. Also exposes Plot.formatNumber(*locale*).
=> formatNumber; filter log tickFormat function

src/channel.js, src/legends.js, src/marks/tip.js, test/output/tipColorLiteral.svg, test/plots/tip.ts
Fixes #2090. Uses a new `channel.defaultScale` field to record what the `channel.scale` _would_ have been, if it weren’t for the specific values provided. This allows the tip mark to detect when a channel would have been associated with the _color_ scale, but isn’t, and hence contains only literal color values that should not be shown (at least by default) in the tip.
=> tip ignores literal colors

src/marker.js, src/memoize.js
Not quite working, but trying to illustrate what I mean in https://github.com/observablehq/plot/pull/2094#pullrequestreview-2124039917. Could probably still be improved…
=> checkpoint markers

docs/.vitepress/config.ts, package.json, yarn.lock
Upgrades to [VitePress 1.3](https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md#130-2024-07-07) which allows us to suppress the in-app appearance switcher in favor of the operating system settings.
=> vitepress 1.3

docs/features/marks.md
=> document arrow support

docs/marks/waffle.md, src/marks/waffle.d.ts, src/marks/waffle.js, test/output/waffleMultiple.svg, test/plots/waffle.ts
Now that we support non-square waffle cells, it feels safe and convenient to support a **multiple** option to affect the number of cells per row (or column, depending on the orientation). I’m not sure about the name of this option, but it seemed desirable to have an orientation-independent name so that it’s easy to switch between waffleX and waffleY.
=> waffle multiple option

docs/marks/rect.md, docs/marks/waffle.md
new notebooks:
* https://observablehq.com/@observablehq/plot-rounded-rects
* https://observablehq.com/@observablehq/plot-simple-waffle
* https://observablehq.com/@observablehq/plot-waffle-group
* https://observablehq.com/@observablehq/plot-waffle-unit
* https://observablehq.com/@observablehq/plot-stacked-waffles (part of Plot gallery)
* https://observablehq.com/@observablehq/plot-survey-waffle (part of Plot gallery)
updated:
* https://observablehq.com/@observablehq/plot-us-choropleth
* https://observablehq.com/@observablehq/plot-live-earthquake-map
* https://observablehq.com/@observablehq/plot-state-centroids
* https://observablehq.com/@observablehq/plot-map-large-multiples
=> link new chart examples to forkable notebooks

src/mark.js, test/output/classNameOnMarks.svg, test/plots/class-name.ts
Fixes #2124 by removing validation of the **className** mark option.
The reason we validate the **className** plot option is because we need to interpolate it into a stylesheet as a selector (prefixed with `.`). That’s not true of the mark-level **className** option, which is simply used to set the `class` attribute. Therefore for the latter we should allow any string, like we do for other attribute mark options such as **ariaLabel** and **ariaDescription**.
=> lax className

docs/.vitepress/config.ts, docs/.vitepress/theme/CustomFooter.vue, docs/.vitepress/theme/ObservablePromo.vue, docs/.vitepress/theme/custom.css
As per design's guidelines.
- Spline Sans Mono for the h1 headers
- Inter for the body text
- Font weight 500 for both
Also made a small fix to the footer (removed an old link)
=> Documentation font changes

docs/.vitepress/theme/custom.css
In looking at the Framework docs, I think we should also change the code font to Spline Sans Mono and set the size and line height to match. 
Also, the `p` line-height is 1.7, so this changes it to 1.5 to match Framework.
=> further design tweaks

docs/.vitepress/theme/custom.css, docs/index.md
Following https://github.com/observablehq/framework/pull/1591 we:
* use the same (sans serif) font on the body
* restore normal weight copy
* adopt phosphate as the brand color
* change the colors in the hero / home page to match
Notes:
* the "soft" color is used for tip backgrounds, it must be very close to the white (or black) background but with the same chroma as phosphate.
* the chroma of the pink colors chosen as alternative is from the Plot logo.
* "Inter" is the default from VitePress
=> design tweaks

docs/.vitepress/theme/custom.css
The phosphate code feels a little “needy” to me — it doesn’t need to be that prominent.
Before:
After:
=> monochrome code

docs/transforms/interval.md
Thanks to the improved date axes, we can simplify these examples.
Before:
After:
=> better interval examples

docs/community.md, docs/why-plot.md
Per new guidelines, we now favor GitHub discussions over the Observable forum and Observable Slack for asking for help.
=> recommend GitHub discussions for help

src/plot.js, test/event-test.js
=> use the context’s document to create the input Event

docs/components/PlotRender.js
#2169 has introduced an error when building the documentation site; this routes around it. I haven't seen a difference in the public-facing result.
(I had mentioned the potential issue here but not seen where it would happen https://github.com/observablehq/plot/pull/2169#discussion_r1755497591)
```
TypeError: Cannot read properties of undefined (reading 'Event')
at context.dispatchValue (file:///Users/fil/Source/plot/docs/.vitepress/.temp/index.C4JK4Fq9.js:6179:59)
at render2 (file:///Users/fil/Source/plot/docs/.vitepress/.temp/index.C4JK4Fq9.js:3542:19)
at Tip.<anonymous> (file:///Users/fil/Source/plot/docs/.vitepress/.temp/index.C4JK4Fq9.js:3583:14)
at Tip.render (file:///Users/fil/Source/plot/docs/.vitepress/.temp/index.C4JK4Fq9.js:3329:15)
at Module.plot …
```
=> fix build error with missing Event

docs/features/marks.md, src/facet.js, src/plot.js, test/output/nestedFacets.html, test/plots/index.ts, test/plots/nested-facets.ts
closes #2218
| before | after |
|--|--|
| ![before](https://github.com/user-attachments/assets/b2f956f3-f292-4523-a444-f7de4e03da6c) |  ![after](https://github.com/user-attachments/assets/97e07283-0d67-4336-88d6-80b5368d12f0) |
(this comment applies to the initial implementation; it would need a different code path now) ~~We could extend this mechanism in the future to accept `HTMLElement` (say, `canvas`, or `DIV`), that we would wrap in a `foreignObject` of the width and height indicated in their style. (Or even text!)~~
=> Fix facet positioning of a rendered rendered SVGSVGElement

package.json, yarn.lock
This wasn’t being used for anything; the imports of `@observablehq/plot` in the tests already worked without it.
=> remove module-alias

src/marks/axis.js, test/output/tickFormatEmptyDomain.svg, test/output/tickFormatEmptyFacetDomain.svg, test/plots/index.ts, test/plots/tick-format.ts
Fixes #2231. If an (ordinal) domain is empty, ignore the **tickFormat** since we can’t infer whether the data is temporal or quantitative, and instead use the default format. This shouldn’t affect the axis as we assume the tick format won’t be used anyway because the domain is empty and hence there can’t be any ticks.
=> fix tickFormat type inference for empty domain

src/scales.js, src/scales/quantitative.js, test/output/colorLegendDomainEmpty.html, test/output/colorLegendDomainUnary.html, test/output/colorLegendLinearDomainEmpty.svg, test/output/colorLegendLinearDomainUnary.svg, test/plots/legend-color.ts
Fixes #2210. Alternative to #2211.
=> handle degenerate domains

docs/features/legends.md, src/legends.d.ts, src/legends.js, src/legends/swatches.js, src/plot.d.ts, src/scales.d.ts, test/output/colorLegendOrdinalRampInline.html, test/plots/athletes-sort.ts, test/plots/decathlon.ts, test/plots/legend-color.ts
This introduces a new top-level **legend** option which is inherited by scales that support legends (_color_, _symbol_, and _opacity_). This makes it slightly more concise to enable legends, and takes us a step closer to enabling them automatically if desired. For example:
```js
Plot.plot({
grid: true,
inset: 12,
legend: true,
marks: [Plot.dot(decathlon, {x: "Long Jump", y: "100 Meters", symbol: "Country", stroke: "Country"})]
})
```
Note above that Plot is smart enough to realize that the _symbol_ legend subsumes the _color_ legend, and hence the _color_ legend does not need to be displayed separately. Plot now suppresses the _color_ legend automatically when the _symbol_ legend also encodes _color_. You can force separate legends by using the **stroke** _symbol_ legend option:
```js …
```
=> top-level legend option, and better types
